# -*- coding: utf-8 -*-
"""plantilla_py1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AILgHr5ccYP9C0knKiTKzx_beecLlhu4
"""

# VARIABLES Y TIPOS BÁSICOS
nombre     = "<texto>"          # String: cadena de texto
edad       = <número>           # Integer: número entero
precio     = <número>.<decimal> # Float: número con decimales
activo     = True               # Boolean: True o False
vacio      = None               # None: ausencia de valor
# LISTAS  (colección ordenada, permite duplicados)
mi_lista = [<elemento1>, <elemento2>, <elemento3>]
mi_lista.append(<nuevo_elemento>)   # Añade al final
mi_lista.remove(<elemento>)         # Elimina la primera ocurrencia
mi_lista[0]                         # Accede al primer elemento (índice 0)
mi_lista[-1]                        # Accede al último elemento
mi_lista[<inicio>:<fin>]            # Slice: trozo de lista
# DICCIONARIOS  (pares clave-valor)
mi_dict = {
    "<clave1>": <valor1>,
    "<clave2>": <valor2>,
}

mi_dict["<clave>"]               # Lee un valor por su clave
mi_dict["<clave>"] = <valor>     # Añade o actualiza una clave
mi_dict.get("<clave>", None)     # Lee sin error si la clave no existe
# CONDICIONALES
if <condición>:
    pass                            # Código si la condición es True
elif <otra_condición>:
    pass                            # Código si la segunda condición es True
else:
    pass                            # Código si ninguna condición se cumple

# Operadores de comparación: ==  !=  >  <  >=  <=
# Operadores lógicos:        and  or  not

# BUCLES

# FOR — recorre cada elemento de una lista (u otro iterable)
for <elemento> in <mi_lista>:
    print(<elemento>)               # Haz algo con cada elemento

# FOR con índice — cuando necesitas saber también la posición
for indice, <elemento> in enumerate(<mi_lista>):
    print(indice, <elemento>)

# FOR con rango — repite N veces (0 hasta N-1)
for i in range(<N>):
    print(i)

# WHILE — repite mientras la condición sea True
while <condición>:
    pass                            # Cuidado: asegúrate de que la condición cambie
    # break    → sale del bucle antes de tiempo
    # continue → salta a la siguiente iteración

# FUNCIONES
def <nombre_funcion>(<param1>, <param2>="<valor_por_defecto>"):
    """
    Descripción breve de lo que hace la función.
    param1: qué es este parámetro
    param2: qué es este parámetro (opcional, por defecto "<valor_por_defecto>")
    """
    resultado = <param1>            # Lógica de la función
    return resultado                # Devuelve el resultado (opcional)

# Llamada a la función
<nombre_funcion>(<valor1>)
<nombre_funcion>(<valor1>, param2="<otro_valor>")   # Con parámetro nombrado

# CLASES
class <NombreClase>:
    """Descripción de la clase."""

    def __init__(self, <atributo1>, <atributo2>):
        # __init__ se ejecuta al crear un objeto de esta clase
        self.<atributo1> = <atributo1>
        self.<atributo2> = <atributo2>

    def <nombre_metodo>(self):
        # Método: función que pertenece a la clase
        return self.<atributo1>

# Crear un objeto (instancia)
mi_objeto = <NombreClase>(<valor1>, <valor2>)
mi_objeto.<nombre_metodo>()         # Llamar a un método del objeto

# MANEJO DE ERRORES
try:
    pass                            # Código que puede fallar
except <TipoDeError> as e:
    print(f"Error: {e}")            # Qué hacer si ocurre ese error
except Exception as e:
    print(f"Error inesperado: {e}") # Captura cualquier otro error
else:
    pass                            # Se ejecuta SOLO si no hubo error
finally:
    pass                            # Se ejecuta SIEMPRE (con o sin error)

# Errores comunes: ValueError, TypeError, KeyError, IndexError, FileNotFoundError

# LECTURA Y ESCRITURA DE ARCHIVOS
# Leer un archivo línea a línea
with open("<ruta/archivo.txt>", "r", encoding="utf-8") as f:
    for linea in f:
        print(linea.strip())        # .strip() elimina saltos de línea y espacios

# Escribir en un archivo ("w" sobreescribe, "a" añade al final)
with open("<ruta/archivo.txt>", "w", encoding="utf-8") as f:
    f.write("<texto a escribir>\n")

# F-STRINGS  (formateo de texto)
nombre = "<nombre>"
edad   = <número>

print(f"Hola, {nombre}. Tienes {edad} años.")           # Básico
print(f"Precio: {<precio>:.2f} €")                      # 2 decimales
print(f"{'centrado':^20}")                              # Centrado en 20 chars

# COMPRENSIÓN DE LISTAS  (forma compacta de crear listas)
# [<expresión> for <elemento> in <iterable> if <condición>]
cuadrados  = [x**2 for x in range(10)]                  # [0, 1, 4, 9, ...]
pares      = [x for x in range(20) if x % 2 == 0]      # Solo los pares
resultado  = [<expresión> for <elem> in <mi_lista> if <condición>]

# IMPORTAR MÓDULOS
import os                           # Módulo completo
import json                         # Para trabajar con JSON
from datetime import datetime       # Solo la clase datetime
from pathlib import Path            # Rutas de archivos modernas

# Ejemplos rápidos
print(os.getcwd())                  # Directorio actual
ahora = datetime.now()              # Fecha y hora actual
ruta  = Path("<carpeta>") / "<archivo.txt>"  # Une rutas de forma segura

# JSON  (leer y escribir datos estructurados)
import json
# Convertir diccionario → string JSON
json_str = json.dumps(<mi_dict>, indent=4, ensure_ascii=False)

# Convertir string JSON → diccionario
mi_dict  = json.loads(<json_str>)

# Leer desde archivo JSON
with open("<archivo.json>", "r", encoding="utf-8") as f:
    datos = json.load(f)

# Guardar en archivo JSON
with open("<archivo.json>", "w", encoding="utf-8") as f:
    json.dump(<mi_dict>, f, indent=4, ensure_ascii=False)